#config/development.yaml
services:
  collector:
    vault-path: stormsync/collector/development
    interval: 10s
  kafka:
    host: kafka-1
    port: 9092
    topic: raw-weather-report
  redis:
    host: redis
    port: 6379
    user: redis_user
    password:
    db: 0
  vault:
    protocol: http
    host: vault
    port: 8200