#config/development.yaml
services:
  collector:
    vault-path: stormsync/collector/development
    interval: 10s
  kafka:
    host: 0.0.0.0
    port: 9092
    user: kafka_user
    password: kafka_password
    topic: raw-weather-report
  redis:
    host: redis
    port: 6200
    user: redis_user
    password: redis_password
    db: 0
  vault:
    protocol: http
    host: vault
    port: 8200