// Code generated by "stringer -type=ReportType"; DO NOT EDIT.

package collector

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hail-0]
	_ = x[Wind-1]
	_ = x[Tornado-2]
}

const _ReportType_name = "HailWindTornado"

var _ReportType_index = [...]uint8{0, 4, 8, 15}

func (i ReportType) String() string {
	if i < 0 || i >= ReportType(len(_ReportType_index)-1) {
		return "ReportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReportType_name[_ReportType_index[i]:_ReportType_index[i+1]]
}
